"""empty message

Revision ID: 104c2c3b8ccb
Revises: 21296606f85f
Create Date: 2024-11-26 21:21:36.044288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104c2c3b8ccb'
down_revision: Union[str, None] = '21296606f85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_dice', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_dice', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_dice', type_='foreignkey')
    op.drop_column('client_dice', 'client_id')
    # ### end Alembic commands ###
