"""empty message

Revision ID: 879e6bb3cc38
Revises: 104c2c3b8ccb
Create Date: 2024-11-26 21:24:24.861942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879e6bb3cc38'
down_revision: Union[str, None] = '104c2c3b8ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_dice', sa.Column('auto_update', sa.Boolean(), nullable=True, comment='По умолчанию заголовок и описание кости автоматически подтягиваются из нфт коллекции'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_dice', 'auto_update')
    # ### end Alembic commands ###
