"""empty message

Revision ID: d4148fe98bf7
Revises: d8c27bb8c44f
Create Date: 2024-11-26 19:28:08.344289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4148fe98bf7'
down_revision: Union[str, None] = 'd8c27bb8c44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('barrels', sa.Integer(), nullable=True))
    op.drop_column('players', 'barrel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('barrel', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'barrels')
    # ### end Alembic commands ###
