"""empty message

Revision ID: d70cd8f7da55
Revises: 457893a7af67
Create Date: 2024-11-26 00:08:20.861895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70cd8f7da55'
down_revision: Union[str, None] = '457893a7af67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_dice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('glb', sa.String(length=200), nullable=True),
    sa.Column('collection', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_dice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_dice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dices', sa.Column('step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dices', 'steps', ['step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dices', type_='foreignkey')
    op.drop_column('dices', 'step_id')
    op.drop_table('client_dice')
    op.drop_table('model_dice')
    # ### end Alembic commands ###
