"""empty message

Revision ID: d8c27bb8c44f
Revises: 43913567ee6c
Create Date: 2024-11-26 19:27:12.517445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c27bb8c44f'
down_revision: Union[str, None] = '43913567ee6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('barrel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'barrel')
    # ### end Alembic commands ###
