"""empty message

Revision ID: e0ca664e4972
Revises: 776edbd79317
Create Date: 2024-10-30 23:12:45.795261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0ca664e4972'
down_revision: Union[str, None] = '776edbd79317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_key', sa.String(length=16), nullable=True))
    op.drop_column('rooms', 'invitation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('invitation', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('rooms', 'room_key')
    # ### end Alembic commands ###
