"""empty message

Revision ID: 41906f71085e
Revises: e0ca664e4972
Create Date: 2024-10-31 20:51:12.027666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41906f71085e'
down_revision: Union[str, None] = 'e0ca664e4972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dices', sa.Column('room_id', sa.Integer(), nullable=True))
    op.drop_constraint('dices_ibfk_1', 'dices', type_='foreignkey')
    op.create_foreign_key(None, 'dices', 'rooms', ['room_id'], ['id'])
    op.drop_column('dices', 'step_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dices', sa.Column('step_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dices', type_='foreignkey')
    op.create_foreign_key('dices_ibfk_1', 'dices', 'steps', ['step_id'], ['id'])
    op.drop_column('dices', 'room_id')
    # ### end Alembic commands ###
