"""empty message

Revision ID: 94a1fa9a27e8
Revises: 41906f71085e
Create Date: 2024-11-01 00:01:36.786677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94a1fa9a27e8'
down_revision: Union[str, None] = '41906f71085e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dices', sa.Column('in_combo', sa.Boolean(), nullable=True))
    op.add_column('steps', sa.Column('is_bolt', sa.Boolean(), nullable=True))
    op.drop_column('steps', 'bolt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('bolt', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('steps', 'is_bolt')
    op.drop_column('dices', 'in_combo')
    # ### end Alembic commands ###
